# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/milad/Documents/Neda-c++praktikum/Project/CppFinalProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/milad/Documents/Neda-c++praktikum/Project/CppFinalProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/milad/Documents/Neda-c++praktikum/Project/CppFinalProject/CMakeFiles /home/milad/Documents/Neda-c++praktikum/Project/CppFinalProject/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/milad/Documents/Neda-c++praktikum/Project/CppFinalProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CppProject

# Build rule for target.
CppProject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CppProject
.PHONY : CppProject

# fast build rule for target.
CppProject/fast:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/build
.PHONY : CppProject/fast

#=============================================================================
# Target rules for targets named CppProject_automoc

# Build rule for target.
CppProject_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CppProject_automoc
.PHONY : CppProject_automoc

# fast build rule for target.
CppProject_automoc/fast:
	$(MAKE) -f CMakeFiles/CppProject_automoc.dir/build.make CMakeFiles/CppProject_automoc.dir/build
.PHONY : CppProject_automoc/fast

CppProject_automoc.o: CppProject_automoc.cpp.o
.PHONY : CppProject_automoc.o

# target to build an object file
CppProject_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/CppProject_automoc.cpp.o
.PHONY : CppProject_automoc.cpp.o

CppProject_automoc.i: CppProject_automoc.cpp.i
.PHONY : CppProject_automoc.i

# target to preprocess a source file
CppProject_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/CppProject_automoc.cpp.i
.PHONY : CppProject_automoc.cpp.i

CppProject_automoc.s: CppProject_automoc.cpp.s
.PHONY : CppProject_automoc.s

# target to generate assembly for a file
CppProject_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/CppProject_automoc.cpp.s
.PHONY : CppProject_automoc.cpp.s

EntryPoint.o: EntryPoint.cpp.o
.PHONY : EntryPoint.o

# target to build an object file
EntryPoint.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/EntryPoint.cpp.o
.PHONY : EntryPoint.cpp.o

EntryPoint.i: EntryPoint.cpp.i
.PHONY : EntryPoint.i

# target to preprocess a source file
EntryPoint.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/EntryPoint.cpp.i
.PHONY : EntryPoint.cpp.i

EntryPoint.s: EntryPoint.cpp.s
.PHONY : EntryPoint.s

# target to generate assembly for a file
EntryPoint.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/EntryPoint.cpp.s
.PHONY : EntryPoint.cpp.s

GetRay.o: GetRay.cpp.o
.PHONY : GetRay.o

# target to build an object file
GetRay.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/GetRay.cpp.o
.PHONY : GetRay.cpp.o

GetRay.i: GetRay.cpp.i
.PHONY : GetRay.i

# target to preprocess a source file
GetRay.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/GetRay.cpp.i
.PHONY : GetRay.cpp.i

GetRay.s: GetRay.cpp.s
.PHONY : GetRay.s

# target to generate assembly for a file
GetRay.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/GetRay.cpp.s
.PHONY : GetRay.cpp.s

MHDHandler.o: MHDHandler.cpp.o
.PHONY : MHDHandler.o

# target to build an object file
MHDHandler.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/MHDHandler.cpp.o
.PHONY : MHDHandler.cpp.o

MHDHandler.i: MHDHandler.cpp.i
.PHONY : MHDHandler.i

# target to preprocess a source file
MHDHandler.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/MHDHandler.cpp.i
.PHONY : MHDHandler.cpp.i

MHDHandler.s: MHDHandler.cpp.s
.PHONY : MHDHandler.s

# target to generate assembly for a file
MHDHandler.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/MHDHandler.cpp.s
.PHONY : MHDHandler.cpp.s

OnTheFlySystemMx.o: OnTheFlySystemMx.cpp.o
.PHONY : OnTheFlySystemMx.o

# target to build an object file
OnTheFlySystemMx.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/OnTheFlySystemMx.cpp.o
.PHONY : OnTheFlySystemMx.cpp.o

OnTheFlySystemMx.i: OnTheFlySystemMx.cpp.i
.PHONY : OnTheFlySystemMx.i

# target to preprocess a source file
OnTheFlySystemMx.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/OnTheFlySystemMx.cpp.i
.PHONY : OnTheFlySystemMx.cpp.i

OnTheFlySystemMx.s: OnTheFlySystemMx.cpp.s
.PHONY : OnTheFlySystemMx.s

# target to generate assembly for a file
OnTheFlySystemMx.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/OnTheFlySystemMx.cpp.s
.PHONY : OnTheFlySystemMx.cpp.s

Part2.o: Part2.cpp.o
.PHONY : Part2.o

# target to build an object file
Part2.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/Part2.cpp.o
.PHONY : Part2.cpp.o

Part2.i: Part2.cpp.i
.PHONY : Part2.i

# target to preprocess a source file
Part2.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/Part2.cpp.i
.PHONY : Part2.cpp.i

Part2.s: Part2.cpp.s
.PHONY : Part2.s

# target to generate assembly for a file
Part2.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/Part2.cpp.s
.PHONY : Part2.cpp.s

RayTracing.o: RayTracing.cpp.o
.PHONY : RayTracing.o

# target to build an object file
RayTracing.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/RayTracing.cpp.o
.PHONY : RayTracing.cpp.o

RayTracing.i: RayTracing.cpp.i
.PHONY : RayTracing.i

# target to preprocess a source file
RayTracing.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/RayTracing.cpp.i
.PHONY : RayTracing.cpp.i

RayTracing.s: RayTracing.cpp.s
.PHONY : RayTracing.s

# target to generate assembly for a file
RayTracing.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/RayTracing.cpp.s
.PHONY : RayTracing.cpp.s

RenderPaint.o: RenderPaint.cpp.o
.PHONY : RenderPaint.o

# target to build an object file
RenderPaint.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/RenderPaint.cpp.o
.PHONY : RenderPaint.cpp.o

RenderPaint.i: RenderPaint.cpp.i
.PHONY : RenderPaint.i

# target to preprocess a source file
RenderPaint.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/RenderPaint.cpp.i
.PHONY : RenderPaint.cpp.i

RenderPaint.s: RenderPaint.cpp.s
.PHONY : RenderPaint.s

# target to generate assembly for a file
RenderPaint.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/RenderPaint.cpp.s
.PHONY : RenderPaint.cpp.s

SourceDetectorPair.o: SourceDetectorPair.cpp.o
.PHONY : SourceDetectorPair.o

# target to build an object file
SourceDetectorPair.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/SourceDetectorPair.cpp.o
.PHONY : SourceDetectorPair.cpp.o

SourceDetectorPair.i: SourceDetectorPair.cpp.i
.PHONY : SourceDetectorPair.i

# target to preprocess a source file
SourceDetectorPair.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/SourceDetectorPair.cpp.i
.PHONY : SourceDetectorPair.cpp.i

SourceDetectorPair.s: SourceDetectorPair.cpp.s
.PHONY : SourceDetectorPair.s

# target to generate assembly for a file
SourceDetectorPair.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/SourceDetectorPair.cpp.s
.PHONY : SourceDetectorPair.cpp.s

TransferFunction.o: TransferFunction.cpp.o
.PHONY : TransferFunction.o

# target to build an object file
TransferFunction.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/TransferFunction.cpp.o
.PHONY : TransferFunction.cpp.o

TransferFunction.i: TransferFunction.cpp.i
.PHONY : TransferFunction.i

# target to preprocess a source file
TransferFunction.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/TransferFunction.cpp.i
.PHONY : TransferFunction.cpp.i

TransferFunction.s: TransferFunction.cpp.s
.PHONY : TransferFunction.s

# target to generate assembly for a file
TransferFunction.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/TransferFunction.cpp.s
.PHONY : TransferFunction.cpp.s

Volume.o: Volume.cpp.o
.PHONY : Volume.o

# target to build an object file
Volume.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/Volume.cpp.o
.PHONY : Volume.cpp.o

Volume.i: Volume.cpp.i
.PHONY : Volume.i

# target to preprocess a source file
Volume.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/Volume.cpp.i
.PHONY : Volume.cpp.i

Volume.s: Volume.cpp.s
.PHONY : Volume.s

# target to generate assembly for a file
Volume.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/Volume.cpp.s
.PHONY : Volume.cpp.s

window.o: window.cpp.o
.PHONY : window.o

# target to build an object file
window.cpp.o:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/window.cpp.o
.PHONY : window.cpp.o

window.i: window.cpp.i
.PHONY : window.i

# target to preprocess a source file
window.cpp.i:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/window.cpp.i
.PHONY : window.cpp.i

window.s: window.cpp.s
.PHONY : window.s

# target to generate assembly for a file
window.cpp.s:
	$(MAKE) -f CMakeFiles/CppProject.dir/build.make CMakeFiles/CppProject.dir/window.cpp.s
.PHONY : window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CppProject_automoc"
	@echo "... CppProject"
	@echo "... CppProject_automoc.o"
	@echo "... CppProject_automoc.i"
	@echo "... CppProject_automoc.s"
	@echo "... EntryPoint.o"
	@echo "... EntryPoint.i"
	@echo "... EntryPoint.s"
	@echo "... GetRay.o"
	@echo "... GetRay.i"
	@echo "... GetRay.s"
	@echo "... MHDHandler.o"
	@echo "... MHDHandler.i"
	@echo "... MHDHandler.s"
	@echo "... OnTheFlySystemMx.o"
	@echo "... OnTheFlySystemMx.i"
	@echo "... OnTheFlySystemMx.s"
	@echo "... Part2.o"
	@echo "... Part2.i"
	@echo "... Part2.s"
	@echo "... RayTracing.o"
	@echo "... RayTracing.i"
	@echo "... RayTracing.s"
	@echo "... RenderPaint.o"
	@echo "... RenderPaint.i"
	@echo "... RenderPaint.s"
	@echo "... SourceDetectorPair.o"
	@echo "... SourceDetectorPair.i"
	@echo "... SourceDetectorPair.s"
	@echo "... TransferFunction.o"
	@echo "... TransferFunction.i"
	@echo "... TransferFunction.s"
	@echo "... Volume.o"
	@echo "... Volume.i"
	@echo "... Volume.s"
	@echo "... window.o"
	@echo "... window.i"
	@echo "... window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

